from fpdf import FPDF
from datetime import datetime
import os

class PDF(FPDF):
    def header(self):
        # Logo
        # self.image('assets/logo.png', 10, 8, 33) (Optional if you have one)
        self.set_font('Arial', 'B', 15)
        self.cell(80) # Move to right
        self.cell(30, 10, 'NeuroSentinel Clinical Report', 0, 0, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by NeuroSentinel Edge AI', 0, 0, 'C')

def generate_pdf(patient_id, stats, risk_label, filename="report.pdf"):
    pdf = PDF()
    pdf.add_page()
    
    # 1. Patient Info
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Patient ID: {patient_id}", ln=1)
    pdf.cell(200, 10, txt=f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=1)
    pdf.line(10, 30, 200, 30) # Horizontal line
    pdf.ln(10)

    # 2. Executive Summary
    pdf.set_font("Arial", 'B', size=16)
    if "Decline" in risk_label:
        pdf.set_text_color(220, 50, 50) # Red
        pdf.cell(200, 10, txt=f"Assessment: {risk_label.upper()}", ln=1)
    else:
        pdf.set_text_color(50, 150, 50) # Green
        pdf.cell(200, 10, txt=f"Assessment: {risk_label.upper()}", ln=1)
    
    pdf.set_text_color(0, 0, 0) # Reset to black
    pdf.set_font("Arial", size=12)
    pdf.ln(5)
    
    # 3. The Data Table
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(200, 10, txt="Biomarker Analysis:", ln=1, fill=True)
    pdf.ln(5)
    
    col_width = 60
    row_height = 10
    
    data = [
        ("Metric", "Value", "Reference Range"),
        ("Pause Rate", f"{stats['pause_rate']:.2f}", "< 0.40"),
        ("Vocab Richness", f"{stats['vocab_richness']:.2f}", "> 0.50"),
        ("Word Count", f"{stats['word_count']}", "N/A"),
    ]
    
    for row in data:
        for item in row:
            pdf.cell(col_width, row_height, str(item), border=1)
        pdf.ln(row_height)
        
    pdf.ln(10)

    # 4. Clinical Note (The "Why")
    pdf.set_font("Arial", 'B', size=14)
    pdf.cell(200, 10, txt="Clinical Interpretation", ln=1)
    pdf.set_font("Arial", size=12)
    
    if "Decline" in risk_label:
        text = ("The patient exhibited significant acoustic hesitations (Pause Rate > 0.4). "
                "Combined with reduced vocabulary richness, this pattern is consistent with "
                "early-stage anomic aphasia. Immediate neurological consultation is recommended.")
    else:
        text = ("The patient demonstrated fluid speech patterns with normal lexical diversity. "
                "No acoustic markers of cognitive decline were detected at this time.")
        
    pdf.multi_cell(0, 10, text)
    
    # Save
    pdf.output(filename)
    return filename